---
title: "digital_marketing"
output: html_document
date: "2023-11-02"
---

```{r}
library(imputeTS)


data = read.csv("data.csv")

data <- na_mean(data)  # Replace missing values with the mean

```



```{r}
library(corrplot)

correlation_matrix <- cor(data[,-1])

# Create a heatmap of the correlation matrix
corrplot(correlation_matrix, method = "square", type = "upper", tl.cex = 0.5)


```


```{r}
# For now, setting all NA values to 0 (because propensity score matching won't work with 
# missing values)
# May want to think about other ways to deal with these NAs (e.g. replacing them w/ other 
# numbers or excluding certain variables or observations)

# Load package for propensity score matching
library(MatchIt)

# For demonstrative purposes, I'm running my analysis on a sample of 10,000 observations
# from the dataset, since propensity matching takes a while (10 mins) on the overall dataset
mysample <- data[sample(1:nrow(data), 10000, replace=FALSE),]

# R Function for propensity score matching
# 1 to 1 match (because ratio = 1); can change to ratio = 2 for 1 to 2 match 
matchprocess = matchit(adopter ~ lovedTracks + posts + playlists + shouts + tenure,
                data = mysample, method = "nearest", ratio = 1)

# View summary statistics on 'treatment'/'control' groups, before and after matching
# See how the mean difference between the 2 groups decreases significantly after matching
summary(matchprocess)

# Export the matched observations to a new dataframe
matchdata<- match.data(matchprocess) 

# See how this new 'matched' dataset now has half adopters and half non adopters
table(matchdata$adopter)
View(matchdata)

```


